### ISSUE TITLE
Even the example didn't work?

### ISSUE THREAD

**Issue by wamson** [yannrichet/jmathplot#16]
I run your example "LinePlotExample" in eclipse. But it comes out a error that "Exception in thread "main" java.lang.NoClassDefFoundError: org/math/io/StringPrintable". help!!!
![qq 20150626212808](https://cloud.githubusercontent.com/assets/4061772/8378203/450e2292-1c4a-11e5-92a5-186a7503fab0.jpg)

![qq 20150626212414](https://cloud.githubusercontent.com/assets/4061772/8378132/ce9f8fa6-1c49-11e5-8a1e-1054b9a42169.jpg)

**Comment by insaneisnotfree** [comment]
You have to include jmathio.jar https://github.com/yannrichet/jmathio

Note. Even this fix won't work; you will have to recreate the jar with icons folder from the source.

**Comment by wamson** [comment]
Oh, how to recreate the jar with icons folder from the source?

**Comment by skipperguy12** [comment]
```
Exception in thread "main" java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at org.math.plot.components.PlotToolBar.<init>(PlotToolBar.java:61)
	at org.math.plot.PlotPanel.addPlotToolBar(PlotPanel.java:149)
	at org.math.plot.PlotPanel.<init>(PlotPanel.java:59)
	at org.math.plot.PlotPanel.<init>(PlotPanel.java:67)
	at org.math.plot.Plot2DPanel.<init>(Plot2DPanel.java:31)
	at online.InitialData.plotData(InitialData.java:15)
	at online.TestGradDescent.main(TestGradDescent.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by wamson** [comment]
I have the same problem as "skipperguy12".
Exception in thread "main" java.lang.NullPointerException
    at javax.swing.ImageIcon.<init>(ImageIcon.java:217)
    at org.math.plot.components.PlotToolBar.<init>(PlotToolBar.java:61)
    at org.math.plot.PlotPanel.addPlotToolBar(PlotPanel.java:149)
    at org.math.plot.PlotPanel.<init>(PlotPanel.java:59)
    at org.math.plot.PlotPanel.<init>(PlotPanel.java:67)
    at org.math.plot.Plot2DPanel.<init>(Plot2DPanel.java:31)
    at online.InitialData.plotData(InitialData.java:15)
    at online.TestGradDescent.main(TestGradDescent.java:10)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

**Comment by yannrichet** [comment]
might be due to maven, not copying .png files in the jar, unlike ant. Probably need to move .png files in the src/main/resources/... directory. Let me some time to check that.

**Comment by yannrichet** [comment]
fixed in last push.

**Comment by PaulojsGoncalves** [comment]
I place last version of jmathplot.jar with fix #16 into libraries of my project using Netbeans IDE. The method Plot2DPanel was now recognized but when I run project next exception was thrown:

Exception in thread "main" java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at org.math.plot.components.PlotToolBar.<init>(PlotToolBar.java:61)
	at org.math.plot.PlotPanel.addPlotToolBar(PlotPanel.java:149)
	at org.math.plot.PlotPanel.<init>(PlotPanel.java:59)
	at org.math.plot.PlotPanel.<init>(PlotPanel.java:67)
	at org.math.plot.Plot2DPanel.<init>(Plot2DPanel.java:31)
	at runningactivitiesannalyser.PlotRunningData.plotgraph(PlotRunningData.java:38)
	at runningactivitiesannalyser.RunningActivitiesAnnalyser.main(RunningActivitiesAnnalyser.java:55)
Java Result: 1

How can I solve the problem and use this method?

Thank you!

**Comment by yannrichet** [comment]
Could you please check that .png files are located inside the jar file ?
Thx

**Comment by PaulojsGoncalves** [comment]
There are no .png files inside jar fie. Only java classes can be found into jar.

**Comment by wamson** [comment]
oh, I put the latest source file into eclipse and export them as Jar. And then it works.
![qq 20150719131410](https://cloud.githubusercontent.com/assets/4061772/8764631/9a9b8468-2e18-11e5-8b37-3a50cf9f447e.jpg)
![qq 20150719131548](https://cloud.githubusercontent.com/assets/4061772/8764632/9a9c36c4-2e18-11e5-9b31-0fe6c50b2b4e.jpg)

**Comment by yannrichet** [comment]
Ok, so I expect it is ok now. For those who still have problems, please cleanup your jar and rebuild from scratch.

**Comment by isnopitag** [comment]
Well for the error of the icons download this .jar 
and dont forget to include jmathio.jar https://github.com/yannrichet/jmathio 

Link for the new jar :v: 
http://www.mediafire.com/download/wa3g3jfs6hv6aif/jmathplot.jar
Sorry for the mediafire link, I still no0b on Github :v:

**Comment by rayryeng** [comment]
@isnopitag Cheers.  I didn't want to rebuild the source again. Thanks so much for making the JAR available!

**Comment by rodanmuro** [comment]
I have the same problem
Exception in thread "main" java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at org.math.plot.components.PlotToolBar.<init>(PlotToolBar.java:61)
	at org.math.plot.PlotPanel.addPlotToolBar(PlotPanel.java:149)
	at org.math.plot.PlotPanel.<init>(PlotPanel.java:59)
	at org.math.plot.PlotPanel.<init>(PlotPanel.java:67)
	at org.math.plot.Plot2DPanel.<init>(Plot2DPanel.java:31)
	at graficasjava.GraficasJava.main(GraficasJava.java:21)
I download the last .jar and nothing
Any help? Thanks
