### ISSUE TITLE
Icons missing from JAR file?

### ISSUE THREAD

**Issue by imagingbook** [yannrichet/jmathplot#25]
Shouldn't the icons (resources) in package org.math.plot.icons be contained in the distributed JAR file? They used to be in the older ZIP files but I cannot find them and a runtime (NullPointer) exception is thrown:

Exception in thread "main" java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(Unknown Source)
	at org.math.plot.components.PlotToolBar.<init>(PlotToolBar.java:61)
	at org.math.plot.PlotPanel.addPlotToolBar(PlotPanel.java:149)
	at org.math.plot.PlotPanel.<init>(PlotPanel.java:59)
	at org.math.plot.PlotPanel.<init>(PlotPanel.java:67)
	at org.math.plot.Plot2DPanel.<init>(Plot2DPanel.java:31)

**Comment by ahooper** [comment]
same problem (with Plot3DPanel)
