### ISSUE TITLE
How could I render to Image in headless mode?

### ISSUE THREAD

**Issue by lordoftheflies** [yannrichet/jmathplot#32]
I'm want to render some high definition data volume as a chart from image and serve as a web image resource.

1. To do this, is there any component out of AWT?

2. Is this a good solution?
- Set the application headless mode
- Render the frame from a PlotCanvas to an image
- Image serve as webresource
```java
// ... at the application initialization
System.setProperty("java.awt.headless", "true");

// ... controller method
        // create your PlotPanel (you can use it as a JPanel)
        Plot2DPanel plot = new Plot2DPanel();

        // add a line plot to the PlotPanel
        plot.addLinePlot("my plot", x, y);
         // Create a buffered image with transparency
        BufferedImage bimage = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);

        // Draw the image on to the buffered image
        Graphics2D bGr = bimage.createGraphics();
        bGr.drawImage(plot.createImage(width, height), 0, 0, null);
        bGr.dispose();

// ... serve the bimage as PNG resource
```

**Comment by javadba** [comment]
This is exactly my question as well.  Constraining the usage to Swing apps kills the usefulness.

**Comment by yannrichet** [comment]
This is the way I use it too.
I know this may be a constraint to use Swing.
When I need more flexible things (like in web apps), I switch to more efficient plot tools, like R.

**Comment by TomtheCoder2** [comment]
Sadly doesnt work anymore:
```
java.awt.HeadlessException
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:165)
	at java.desktop/java.awt.Window.<init>(Window.java:549)
	at java.desktop/java.awt.Frame.<init>(Frame.java:426)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
	at org.math.plot.components.ScalesFrame.<init>(ScalesFrame.java:30)
	at org.math.plot.canvas.PlotCanvas.<init>(PlotCanvas.java:491)
	at org.math.plot.canvas.Plot2DCanvas.<init>(Plot2DCanvas.java:25)
	at org.math.plot.Plot2DPanel.<init>(Plot2DPanel.java:31)
	at mindustry.plugin.utils.plot.PlotTests.test3(PlotTests.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```
![image](https://user-images.githubusercontent.com/57863175/184724253-d17b5709-d0bf-4ff9-bda7-9bcc31de7b6f.png)
