### ISSUE TITLE
This library worked just on Eclips or not ?

### ISSUE THREAD

**Issue by enghelab** [yannrichet/jmathplot#40]
I have a problem , i working with intellijIdea and get below error : 
Exception in thread "main" java.lang.NoClassDefFoundError: org/math/io/StringPrintable
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.math.plot.canvas.PlotCanvas.<init>(PlotCanvas.java:491)
	at org.math.plot.canvas.Plot2DCanvas.<init>(Plot2DCanvas.java:25)
	at org.math.plot.Plot2DPanel.<init>(Plot2DPanel.java:31)
	at FFT.main(FFT.java:110)
Caused by: java.lang.ClassNotFoundException: org.math.io.StringPrintable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by yannrichet** [comment]
You probably need to add jmathio.jar dependency explicitely in your
classpath, also.

**Comment by giuseppeCruised** [comment]
Had the same issue and after adding jmathio.jar dependency i got:
Exception in thread "main" java.lang.NullPointerException
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at org.math.plot.components.PlotToolBar.<init>(PlotToolBar.java:61)
	at org.math.plot.PlotPanel.addPlotToolBar(PlotPanel.java:149)
	at org.math.plot.PlotPanel.<init>(PlotPanel.java:59)
	at org.math.plot.PlotPanel.<init>(PlotPanel.java:67)
	at org.math.plot.Plot2DPanel.<init>(Plot2DPanel.java:31)
	at main.main(main.java:19)

I think i will just use a different library...
