### ISSUE TITLE
NullPointer

### ISSUE THREAD

**Issue by BadShun** [yannrichet/jmathplot#43]
I have a problem , i working with intellijIdea and get below error :
Exception in thread "main" java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at org.math.plot.components.PlotToolBar.<init>(PlotToolBar.java:61)
	at org.math.plot.PlotPanel.addPlotToolBar(PlotPanel.java:149)
	at org.math.plot.PlotPanel.<init>(PlotPanel.java:59)
	at org.math.plot.PlotPanel.<init>(PlotPanel.java:67)
	at org.math.plot.Plot2DPanel.<init>(Plot2DPanel.java:31)
	at Test.main(Test.java:12)

my code:
import javax.swing.*;

import org.math.plot.*;

public class Test {
    public static void main(String[] args) {

        double[] x = { 1, 2, 3, 4, 5, 6 };
        double[] y = { 45, 89, 6, 32, 63, 12 };

        Plot2DPanel plot = new Plot2DPanel();

        plot.addLinePlot("my plot", x, y);

        JFrame frame = new JFrame("a plot panel");
        frame.setSize(600, 600);
        frame.setContentPane(plot);
        frame.setVisible(true);

    }
}

**Comment by yannrichet** [comment]
Hi. 
You probably miss some resources, like icons images...

**Comment by etienz** [comment]
Hi. I am also running into this issue. Do you have any suggestions on how to resolve it?

**Comment by yannrichet** [comment]
Check that you have images & icons in your resources declared in the project.
